// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcWCZcYO5SYvsalsi0Pc8CthCH_ipX61c',
    appId: '1:688835170856:web:dab059b5a4e38e94ccdb1d',
    messagingSenderId: '688835170856',
    projectId: 'ecoscan-5cd4a',
    authDomain: 'ecoscan-5cd4a.firebaseapp.com',
    storageBucket: 'ecoscan-5cd4a.firebasestorage.app',
    measurementId: 'G-5RQDZLDP61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDILHMPy0-bB5VonY5aPzT-Gvc21iG90iw',
    appId: '1:688835170856:android:5c740cd6516a3f79ccdb1d',
    messagingSenderId: '688835170856',
    projectId: 'ecoscan-5cd4a',
    storageBucket: 'ecoscan-5cd4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6fAHn8AoqhTnR1wvW84ef4P9D6TuNTF4',
    appId: '1:688835170856:ios:cffbba05d6e280a6ccdb1d',
    messagingSenderId: '688835170856',
    projectId: 'ecoscan-5cd4a',
    storageBucket: 'ecoscan-5cd4a.firebasestorage.app',
    iosClientId: '688835170856-or2nssq958ms6degs5t2f7fm051vg4nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.recyclingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6fAHn8AoqhTnR1wvW84ef4P9D6TuNTF4',
    appId: '1:688835170856:ios:cffbba05d6e280a6ccdb1d',
    messagingSenderId: '688835170856',
    projectId: 'ecoscan-5cd4a',
    storageBucket: 'ecoscan-5cd4a.firebasestorage.app',
    iosClientId: '688835170856-or2nssq958ms6degs5t2f7fm051vg4nf.apps.googleusercontent.com',
    iosBundleId: 'com.example.recyclingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcWCZcYO5SYvsalsi0Pc8CthCH_ipX61c',
    appId: '1:688835170856:web:ff65922df1c06cbbccdb1d',
    messagingSenderId: '688835170856',
    projectId: 'ecoscan-5cd4a',
    authDomain: 'ecoscan-5cd4a.firebaseapp.com',
    storageBucket: 'ecoscan-5cd4a.firebasestorage.app',
    measurementId: 'G-CGEPLNHP5Q',
  );
}
